name: Report an issue with the Mammotion Intergration
description: Report an issue with the Mammotion Intergration.
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: dropdown
    id: robot
    validations:
      required: true
    attributes:
      label: What Mammotion mower are you using?
      options:
        - Luba 1
        - Luba 2
        - Luba 2x
        - Luba mini
        - Yuka
        - Yuka 2
        - Yuka mini
  - type: input
    id: intergration_version
    validations:
      required: true
    attributes:
      label: What version of the Mammotion intergration are you using?
      placeholder: 4280d63, unsure
  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core are you running?
      placeholder: core-
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)

